### PR TITLE
Add TRACK_HINTS.md

### PR DESCRIPTION
**Pull request by mhinz**

### CODE REVIEW

**Comment by kytrinyx** [comment]
The documentation for this is outdated (I just realized this yesterday, but haven't gotten it fixed yet). The name of the document should be `TRACK_HINTS.md` (`SETUP.md` will still work, but it's deprecated).

**Comment by kotp** [comment]
Other than the filename, it looks good to me.

**Comment by mhinz** [comment]
Oops! I'll rename it.

**Comment by kytrinyx** [comment]
✨ Thanks!

**Pull request merged**
